[default]
ffi = true
fuzz_runs = 256
optimizer = true
optimizer_runs = 200
remappings = [
  "ds-test/=lib/ds-test/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]
verbosity = 3
gas_reports = ["*"]

[ci]
fuzz_runs = 4096
verbosity = 5
